# Generated by Django 5.2.5 on 2025-08-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='daily_rate',
            new_name='daily_rent',
        ),
    ]
