# Generated by Django 5.2.5 on 2025-08-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_daily_rate_movie_daily_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
