# Generated by Django 5.2.5 on 2025-09-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_tag_movie_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.FileField(null=True, upload_to='movie_images'),
        ),
    ]
