# Generated by Django 5.2.5 on 2025-09-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='movie_images/movie_cover_placeholder.png', upload_to='movie_images'),
        ),
    ]
