# Generated by Django 6.0 on 2025-12-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='number_in_stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(),
        ),
    ]
